//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ProxiBusNicPBN.proxibusnicweb {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProxiBusNicWSSoap", Namespace="http://tempuri.org/")]
    public partial class ProxiBusNicWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AgregarParadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarParadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditarParadasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarParadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarParadaActivasOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditarBusParadasOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarBusParadasOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarBusesParadasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarBusParadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarBusOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarBusOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarBusOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarBusActivosOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditarBusOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarSugerenciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditarSugerenciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminaraSugerenciasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarSugerenciasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarSugerenciasPersonalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback RolAnonimoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CambiarClaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearUsuarioRolOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProxiBusNicWS() {
            this.Url = "http://proxibusnicweb.somee.com/ProxiBusNicWeb/ProxiBusNicWS.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AgregarParadaCompletedEventHandler AgregarParadaCompleted;
        
        /// <remarks/>
        public event EliminarParadaCompletedEventHandler EliminarParadaCompleted;
        
        /// <remarks/>
        public event EditarParadasCompletedEventHandler EditarParadasCompleted;
        
        /// <remarks/>
        public event ListarParadaCompletedEventHandler ListarParadaCompleted;
        
        /// <remarks/>
        public event ListarParadaActivasCompletedEventHandler ListarParadaActivasCompleted;
        
        /// <remarks/>
        public event EditarBusParadasCompletedEventHandler EditarBusParadasCompleted;
        
        /// <remarks/>
        public event AgregarBusParadasCompletedEventHandler AgregarBusParadasCompleted;
        
        /// <remarks/>
        public event EliminarBusesParadasCompletedEventHandler EliminarBusesParadasCompleted;
        
        /// <remarks/>
        public event ListarBusParadaCompletedEventHandler ListarBusParadaCompleted;
        
        /// <remarks/>
        public event AgregarBusCompletedEventHandler AgregarBusCompleted;
        
        /// <remarks/>
        public event EliminarBusCompletedEventHandler EliminarBusCompleted;
        
        /// <remarks/>
        public event ListarBusCompletedEventHandler ListarBusCompleted;
        
        /// <remarks/>
        public event ListarBusActivosCompletedEventHandler ListarBusActivosCompleted;
        
        /// <remarks/>
        public event EditarBusCompletedEventHandler EditarBusCompleted;
        
        /// <remarks/>
        public event AgregarSugerenciaCompletedEventHandler AgregarSugerenciaCompleted;
        
        /// <remarks/>
        public event EditarSugerenciaCompletedEventHandler EditarSugerenciaCompleted;
        
        /// <remarks/>
        public event EliminaraSugerenciasCompletedEventHandler EliminaraSugerenciasCompleted;
        
        /// <remarks/>
        public event ListarSugerenciasCompletedEventHandler ListarSugerenciasCompleted;
        
        /// <remarks/>
        public event ListarSugerenciasPersonalesCompletedEventHandler ListarSugerenciasPersonalesCompleted;
        
        /// <remarks/>
        public event RolAnonimoCompletedEventHandler RolAnonimoCompleted;
        
        /// <remarks/>
        public event CambiarClaveCompletedEventHandler CambiarClaveCompleted;
        
        /// <remarks/>
        public event CrearUsuarioCompletedEventHandler CrearUsuarioCompleted;
        
        /// <remarks/>
        public event ListarUsuariosCompletedEventHandler ListarUsuariosCompleted;
        
        /// <remarks/>
        public event EliminarUsuarioCompletedEventHandler EliminarUsuarioCompleted;
        
        /// <remarks/>
        public event CrearUsuarioRolCompletedEventHandler CrearUsuarioRolCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarParada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AgregarParada(ParadasWS paradasWS) {
            object[] results = this.Invoke("AgregarParada", new object[] {
                        paradasWS});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarParadaAsync(ParadasWS paradasWS) {
            this.AgregarParadaAsync(paradasWS, null);
        }
        
        /// <remarks/>
        public void AgregarParadaAsync(ParadasWS paradasWS, object userState) {
            if ((this.AgregarParadaOperationCompleted == null)) {
                this.AgregarParadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarParadaOperationCompleted);
            }
            this.InvokeAsync("AgregarParada", new object[] {
                        paradasWS}, this.AgregarParadaOperationCompleted, userState);
        }
        
        private void OnAgregarParadaOperationCompleted(object arg) {
            if ((this.AgregarParadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarParadaCompleted(this, new AgregarParadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarParada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoSW EliminarParada(int id) {
            object[] results = this.Invoke("EliminarParada", new object[] {
                        id});
            return ((ResultadoSW)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarParadaAsync(int id) {
            this.EliminarParadaAsync(id, null);
        }
        
        /// <remarks/>
        public void EliminarParadaAsync(int id, object userState) {
            if ((this.EliminarParadaOperationCompleted == null)) {
                this.EliminarParadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarParadaOperationCompleted);
            }
            this.InvokeAsync("EliminarParada", new object[] {
                        id}, this.EliminarParadaOperationCompleted, userState);
        }
        
        private void OnEliminarParadaOperationCompleted(object arg) {
            if ((this.EliminarParadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarParadaCompleted(this, new EliminarParadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditarParadas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int EditarParadas(ParadasWS ParadasWs) {
            object[] results = this.Invoke("EditarParadas", new object[] {
                        ParadasWs});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void EditarParadasAsync(ParadasWS ParadasWs) {
            this.EditarParadasAsync(ParadasWs, null);
        }
        
        /// <remarks/>
        public void EditarParadasAsync(ParadasWS ParadasWs, object userState) {
            if ((this.EditarParadasOperationCompleted == null)) {
                this.EditarParadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditarParadasOperationCompleted);
            }
            this.InvokeAsync("EditarParadas", new object[] {
                        ParadasWs}, this.EditarParadasOperationCompleted, userState);
        }
        
        private void OnEditarParadasOperationCompleted(object arg) {
            if ((this.EditarParadasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditarParadasCompleted(this, new EditarParadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarParada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ParadasWS[] ListarParada() {
            object[] results = this.Invoke("ListarParada", new object[0]);
            return ((ParadasWS[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarParadaAsync() {
            this.ListarParadaAsync(null);
        }
        
        /// <remarks/>
        public void ListarParadaAsync(object userState) {
            if ((this.ListarParadaOperationCompleted == null)) {
                this.ListarParadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarParadaOperationCompleted);
            }
            this.InvokeAsync("ListarParada", new object[0], this.ListarParadaOperationCompleted, userState);
        }
        
        private void OnListarParadaOperationCompleted(object arg) {
            if ((this.ListarParadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarParadaCompleted(this, new ListarParadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarParadaActivas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ParadasWS[] ListarParadaActivas() {
            object[] results = this.Invoke("ListarParadaActivas", new object[0]);
            return ((ParadasWS[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarParadaActivasAsync() {
            this.ListarParadaActivasAsync(null);
        }
        
        /// <remarks/>
        public void ListarParadaActivasAsync(object userState) {
            if ((this.ListarParadaActivasOperationCompleted == null)) {
                this.ListarParadaActivasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarParadaActivasOperationCompleted);
            }
            this.InvokeAsync("ListarParadaActivas", new object[0], this.ListarParadaActivasOperationCompleted, userState);
        }
        
        private void OnListarParadaActivasOperationCompleted(object arg) {
            if ((this.ListarParadaActivasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarParadaActivasCompleted(this, new ListarParadaActivasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditarBusParadas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int EditarBusParadas(BusParadaWS busParadaWs) {
            object[] results = this.Invoke("EditarBusParadas", new object[] {
                        busParadaWs});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void EditarBusParadasAsync(BusParadaWS busParadaWs) {
            this.EditarBusParadasAsync(busParadaWs, null);
        }
        
        /// <remarks/>
        public void EditarBusParadasAsync(BusParadaWS busParadaWs, object userState) {
            if ((this.EditarBusParadasOperationCompleted == null)) {
                this.EditarBusParadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditarBusParadasOperationCompleted);
            }
            this.InvokeAsync("EditarBusParadas", new object[] {
                        busParadaWs}, this.EditarBusParadasOperationCompleted, userState);
        }
        
        private void OnEditarBusParadasOperationCompleted(object arg) {
            if ((this.EditarBusParadasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditarBusParadasCompleted(this, new EditarBusParadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarBusParadas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AgregarBusParadas(BusParadaWS busParadaWS) {
            object[] results = this.Invoke("AgregarBusParadas", new object[] {
                        busParadaWS});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarBusParadasAsync(BusParadaWS busParadaWS) {
            this.AgregarBusParadasAsync(busParadaWS, null);
        }
        
        /// <remarks/>
        public void AgregarBusParadasAsync(BusParadaWS busParadaWS, object userState) {
            if ((this.AgregarBusParadasOperationCompleted == null)) {
                this.AgregarBusParadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarBusParadasOperationCompleted);
            }
            this.InvokeAsync("AgregarBusParadas", new object[] {
                        busParadaWS}, this.AgregarBusParadasOperationCompleted, userState);
        }
        
        private void OnAgregarBusParadasOperationCompleted(object arg) {
            if ((this.AgregarBusParadasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarBusParadasCompleted(this, new AgregarBusParadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarBusesParadas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoSW EliminarBusesParadas(int id) {
            object[] results = this.Invoke("EliminarBusesParadas", new object[] {
                        id});
            return ((ResultadoSW)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarBusesParadasAsync(int id) {
            this.EliminarBusesParadasAsync(id, null);
        }
        
        /// <remarks/>
        public void EliminarBusesParadasAsync(int id, object userState) {
            if ((this.EliminarBusesParadasOperationCompleted == null)) {
                this.EliminarBusesParadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarBusesParadasOperationCompleted);
            }
            this.InvokeAsync("EliminarBusesParadas", new object[] {
                        id}, this.EliminarBusesParadasOperationCompleted, userState);
        }
        
        private void OnEliminarBusesParadasOperationCompleted(object arg) {
            if ((this.EliminarBusesParadasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarBusesParadasCompleted(this, new EliminarBusesParadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarBusParada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BusParadaWS[] ListarBusParada() {
            object[] results = this.Invoke("ListarBusParada", new object[0]);
            return ((BusParadaWS[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarBusParadaAsync() {
            this.ListarBusParadaAsync(null);
        }
        
        /// <remarks/>
        public void ListarBusParadaAsync(object userState) {
            if ((this.ListarBusParadaOperationCompleted == null)) {
                this.ListarBusParadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarBusParadaOperationCompleted);
            }
            this.InvokeAsync("ListarBusParada", new object[0], this.ListarBusParadaOperationCompleted, userState);
        }
        
        private void OnListarBusParadaOperationCompleted(object arg) {
            if ((this.ListarBusParadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarBusParadaCompleted(this, new ListarBusParadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarBus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AgregarBus(BusWS busWS) {
            object[] results = this.Invoke("AgregarBus", new object[] {
                        busWS});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarBusAsync(BusWS busWS) {
            this.AgregarBusAsync(busWS, null);
        }
        
        /// <remarks/>
        public void AgregarBusAsync(BusWS busWS, object userState) {
            if ((this.AgregarBusOperationCompleted == null)) {
                this.AgregarBusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarBusOperationCompleted);
            }
            this.InvokeAsync("AgregarBus", new object[] {
                        busWS}, this.AgregarBusOperationCompleted, userState);
        }
        
        private void OnAgregarBusOperationCompleted(object arg) {
            if ((this.AgregarBusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarBusCompleted(this, new AgregarBusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarBus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoSW EliminarBus(int id) {
            object[] results = this.Invoke("EliminarBus", new object[] {
                        id});
            return ((ResultadoSW)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarBusAsync(int id) {
            this.EliminarBusAsync(id, null);
        }
        
        /// <remarks/>
        public void EliminarBusAsync(int id, object userState) {
            if ((this.EliminarBusOperationCompleted == null)) {
                this.EliminarBusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarBusOperationCompleted);
            }
            this.InvokeAsync("EliminarBus", new object[] {
                        id}, this.EliminarBusOperationCompleted, userState);
        }
        
        private void OnEliminarBusOperationCompleted(object arg) {
            if ((this.EliminarBusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarBusCompleted(this, new EliminarBusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarBus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BusWS[] ListarBus() {
            object[] results = this.Invoke("ListarBus", new object[0]);
            return ((BusWS[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarBusAsync() {
            this.ListarBusAsync(null);
        }
        
        /// <remarks/>
        public void ListarBusAsync(object userState) {
            if ((this.ListarBusOperationCompleted == null)) {
                this.ListarBusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarBusOperationCompleted);
            }
            this.InvokeAsync("ListarBus", new object[0], this.ListarBusOperationCompleted, userState);
        }
        
        private void OnListarBusOperationCompleted(object arg) {
            if ((this.ListarBusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarBusCompleted(this, new ListarBusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarBusActivos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BusWS[] ListarBusActivos() {
            object[] results = this.Invoke("ListarBusActivos", new object[0]);
            return ((BusWS[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarBusActivosAsync() {
            this.ListarBusActivosAsync(null);
        }
        
        /// <remarks/>
        public void ListarBusActivosAsync(object userState) {
            if ((this.ListarBusActivosOperationCompleted == null)) {
                this.ListarBusActivosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarBusActivosOperationCompleted);
            }
            this.InvokeAsync("ListarBusActivos", new object[0], this.ListarBusActivosOperationCompleted, userState);
        }
        
        private void OnListarBusActivosOperationCompleted(object arg) {
            if ((this.ListarBusActivosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarBusActivosCompleted(this, new ListarBusActivosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditarBus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int EditarBus(BusWS busWs) {
            object[] results = this.Invoke("EditarBus", new object[] {
                        busWs});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void EditarBusAsync(BusWS busWs) {
            this.EditarBusAsync(busWs, null);
        }
        
        /// <remarks/>
        public void EditarBusAsync(BusWS busWs, object userState) {
            if ((this.EditarBusOperationCompleted == null)) {
                this.EditarBusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditarBusOperationCompleted);
            }
            this.InvokeAsync("EditarBus", new object[] {
                        busWs}, this.EditarBusOperationCompleted, userState);
        }
        
        private void OnEditarBusOperationCompleted(object arg) {
            if ((this.EditarBusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditarBusCompleted(this, new EditarBusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarSugerencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AgregarSugerencia(SugerenciaWS sugerenciaWS) {
            object[] results = this.Invoke("AgregarSugerencia", new object[] {
                        sugerenciaWS});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarSugerenciaAsync(SugerenciaWS sugerenciaWS) {
            this.AgregarSugerenciaAsync(sugerenciaWS, null);
        }
        
        /// <remarks/>
        public void AgregarSugerenciaAsync(SugerenciaWS sugerenciaWS, object userState) {
            if ((this.AgregarSugerenciaOperationCompleted == null)) {
                this.AgregarSugerenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarSugerenciaOperationCompleted);
            }
            this.InvokeAsync("AgregarSugerencia", new object[] {
                        sugerenciaWS}, this.AgregarSugerenciaOperationCompleted, userState);
        }
        
        private void OnAgregarSugerenciaOperationCompleted(object arg) {
            if ((this.AgregarSugerenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarSugerenciaCompleted(this, new AgregarSugerenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditarSugerencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int EditarSugerencia(SugerenciaWS sugerenciaWS) {
            object[] results = this.Invoke("EditarSugerencia", new object[] {
                        sugerenciaWS});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void EditarSugerenciaAsync(SugerenciaWS sugerenciaWS) {
            this.EditarSugerenciaAsync(sugerenciaWS, null);
        }
        
        /// <remarks/>
        public void EditarSugerenciaAsync(SugerenciaWS sugerenciaWS, object userState) {
            if ((this.EditarSugerenciaOperationCompleted == null)) {
                this.EditarSugerenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditarSugerenciaOperationCompleted);
            }
            this.InvokeAsync("EditarSugerencia", new object[] {
                        sugerenciaWS}, this.EditarSugerenciaOperationCompleted, userState);
        }
        
        private void OnEditarSugerenciaOperationCompleted(object arg) {
            if ((this.EditarSugerenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditarSugerenciaCompleted(this, new EditarSugerenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminaraSugerencias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoSW EliminaraSugerencias(int id) {
            object[] results = this.Invoke("EliminaraSugerencias", new object[] {
                        id});
            return ((ResultadoSW)(results[0]));
        }
        
        /// <remarks/>
        public void EliminaraSugerenciasAsync(int id) {
            this.EliminaraSugerenciasAsync(id, null);
        }
        
        /// <remarks/>
        public void EliminaraSugerenciasAsync(int id, object userState) {
            if ((this.EliminaraSugerenciasOperationCompleted == null)) {
                this.EliminaraSugerenciasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminaraSugerenciasOperationCompleted);
            }
            this.InvokeAsync("EliminaraSugerencias", new object[] {
                        id}, this.EliminaraSugerenciasOperationCompleted, userState);
        }
        
        private void OnEliminaraSugerenciasOperationCompleted(object arg) {
            if ((this.EliminaraSugerenciasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminaraSugerenciasCompleted(this, new EliminaraSugerenciasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarSugerencias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SugerenciaWS[] ListarSugerencias() {
            object[] results = this.Invoke("ListarSugerencias", new object[0]);
            return ((SugerenciaWS[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarSugerenciasAsync() {
            this.ListarSugerenciasAsync(null);
        }
        
        /// <remarks/>
        public void ListarSugerenciasAsync(object userState) {
            if ((this.ListarSugerenciasOperationCompleted == null)) {
                this.ListarSugerenciasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarSugerenciasOperationCompleted);
            }
            this.InvokeAsync("ListarSugerencias", new object[0], this.ListarSugerenciasOperationCompleted, userState);
        }
        
        private void OnListarSugerenciasOperationCompleted(object arg) {
            if ((this.ListarSugerenciasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarSugerenciasCompleted(this, new ListarSugerenciasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarSugerenciasPersonales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SugerenciaWS[] ListarSugerenciasPersonales(string correo) {
            object[] results = this.Invoke("ListarSugerenciasPersonales", new object[] {
                        correo});
            return ((SugerenciaWS[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarSugerenciasPersonalesAsync(string correo) {
            this.ListarSugerenciasPersonalesAsync(correo, null);
        }
        
        /// <remarks/>
        public void ListarSugerenciasPersonalesAsync(string correo, object userState) {
            if ((this.ListarSugerenciasPersonalesOperationCompleted == null)) {
                this.ListarSugerenciasPersonalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarSugerenciasPersonalesOperationCompleted);
            }
            this.InvokeAsync("ListarSugerenciasPersonales", new object[] {
                        correo}, this.ListarSugerenciasPersonalesOperationCompleted, userState);
        }
        
        private void OnListarSugerenciasPersonalesOperationCompleted(object arg) {
            if ((this.ListarSugerenciasPersonalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarSugerenciasPersonalesCompleted(this, new ListarSugerenciasPersonalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RolAnonimo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RolAnonimo(string correo) {
            object[] results = this.Invoke("RolAnonimo", new object[] {
                        correo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RolAnonimoAsync(string correo) {
            this.RolAnonimoAsync(correo, null);
        }
        
        /// <remarks/>
        public void RolAnonimoAsync(string correo, object userState) {
            if ((this.RolAnonimoOperationCompleted == null)) {
                this.RolAnonimoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRolAnonimoOperationCompleted);
            }
            this.InvokeAsync("RolAnonimo", new object[] {
                        correo}, this.RolAnonimoOperationCompleted, userState);
        }
        
        private void OnRolAnonimoOperationCompleted(object arg) {
            if ((this.RolAnonimoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RolAnonimoCompleted(this, new RolAnonimoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CambiarClave", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CambiarClave(string correo, string Pass) {
            object[] results = this.Invoke("CambiarClave", new object[] {
                        correo,
                        Pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CambiarClaveAsync(string correo, string Pass) {
            this.CambiarClaveAsync(correo, Pass, null);
        }
        
        /// <remarks/>
        public void CambiarClaveAsync(string correo, string Pass, object userState) {
            if ((this.CambiarClaveOperationCompleted == null)) {
                this.CambiarClaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCambiarClaveOperationCompleted);
            }
            this.InvokeAsync("CambiarClave", new object[] {
                        correo,
                        Pass}, this.CambiarClaveOperationCompleted, userState);
        }
        
        private void OnCambiarClaveOperationCompleted(object arg) {
            if ((this.CambiarClaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CambiarClaveCompleted(this, new CambiarClaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoSW CrearUsuario(string Email, string Pass) {
            object[] results = this.Invoke("CrearUsuario", new object[] {
                        Email,
                        Pass});
            return ((ResultadoSW)(results[0]));
        }
        
        /// <remarks/>
        public void CrearUsuarioAsync(string Email, string Pass) {
            this.CrearUsuarioAsync(Email, Pass, null);
        }
        
        /// <remarks/>
        public void CrearUsuarioAsync(string Email, string Pass, object userState) {
            if ((this.CrearUsuarioOperationCompleted == null)) {
                this.CrearUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearUsuarioOperationCompleted);
            }
            this.InvokeAsync("CrearUsuario", new object[] {
                        Email,
                        Pass}, this.CrearUsuarioOperationCompleted, userState);
        }
        
        private void OnCrearUsuarioOperationCompleted(object arg) {
            if ((this.CrearUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearUsuarioCompleted(this, new CrearUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarUsuarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsuariosWS[] ListarUsuarios() {
            object[] results = this.Invoke("ListarUsuarios", new object[0]);
            return ((UsuariosWS[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarUsuariosAsync() {
            this.ListarUsuariosAsync(null);
        }
        
        /// <remarks/>
        public void ListarUsuariosAsync(object userState) {
            if ((this.ListarUsuariosOperationCompleted == null)) {
                this.ListarUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarUsuariosOperationCompleted);
            }
            this.InvokeAsync("ListarUsuarios", new object[0], this.ListarUsuariosOperationCompleted, userState);
        }
        
        private void OnListarUsuariosOperationCompleted(object arg) {
            if ((this.ListarUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarUsuariosCompleted(this, new ListarUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoSW EliminarUsuario(string Email) {
            object[] results = this.Invoke("EliminarUsuario", new object[] {
                        Email});
            return ((ResultadoSW)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarUsuarioAsync(string Email) {
            this.EliminarUsuarioAsync(Email, null);
        }
        
        /// <remarks/>
        public void EliminarUsuarioAsync(string Email, object userState) {
            if ((this.EliminarUsuarioOperationCompleted == null)) {
                this.EliminarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarUsuarioOperationCompleted);
            }
            this.InvokeAsync("EliminarUsuario", new object[] {
                        Email}, this.EliminarUsuarioOperationCompleted, userState);
        }
        
        private void OnEliminarUsuarioOperationCompleted(object arg) {
            if ((this.EliminarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarUsuarioCompleted(this, new EliminarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearUsuarioRol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoSW CrearUsuarioRol(string Email, string Pass, string rol) {
            object[] results = this.Invoke("CrearUsuarioRol", new object[] {
                        Email,
                        Pass,
                        rol});
            return ((ResultadoSW)(results[0]));
        }
        
        /// <remarks/>
        public void CrearUsuarioRolAsync(string Email, string Pass, string rol) {
            this.CrearUsuarioRolAsync(Email, Pass, rol, null);
        }
        
        /// <remarks/>
        public void CrearUsuarioRolAsync(string Email, string Pass, string rol, object userState) {
            if ((this.CrearUsuarioRolOperationCompleted == null)) {
                this.CrearUsuarioRolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearUsuarioRolOperationCompleted);
            }
            this.InvokeAsync("CrearUsuarioRol", new object[] {
                        Email,
                        Pass,
                        rol}, this.CrearUsuarioRolOperationCompleted, userState);
        }
        
        private void OnCrearUsuarioRolOperationCompleted(object arg) {
            if ((this.CrearUsuarioRolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearUsuarioRolCompleted(this, new CrearUsuarioRolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Login(string cuenta, string Pass) {
            object[] results = this.Invoke("Login", new object[] {
                        cuenta,
                        Pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string cuenta, string Pass) {
            this.LoginAsync(cuenta, Pass, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string cuenta, string Pass, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        cuenta,
                        Pass}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ParadasWS {
        
        private int idField;
        
        private string descripcionField;
        
        private string aliasField;
        
        private byte[] fotoParadaField;
        
        private bool estadoField;
        
        private string longitudField;
        
        private string latitudField;
        
        private string fechaCreacionField;
        
        private string usuarioCreacionField;
        
        private string fechaModificacionField;
        
        private string usuarioModificacionField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FotoParada {
            get {
                return this.fotoParadaField;
            }
            set {
                this.fotoParadaField = value;
            }
        }
        
        /// <remarks/>
        public bool Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
            }
        }
        
        /// <remarks/>
        public string Latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
            }
        }
        
        /// <remarks/>
        public string FechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
            }
        }
        
        /// <remarks/>
        public string FechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioModificacion {
            get {
                return this.usuarioModificacionField;
            }
            set {
                this.usuarioModificacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuariosWS {
        
        private string idField;
        
        private string correoField;
        
        private string claveField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
        
        /// <remarks/>
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SugerenciaWS {
        
        private int idField;
        
        private string descripcionSugerenciaField;
        
        private string usuarioCreacionField;
        
        private string fechaCreacionField;
        
        private int paradaIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string DescripcionSugerencia {
            get {
                return this.descripcionSugerenciaField;
            }
            set {
                this.descripcionSugerenciaField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
            }
        }
        
        /// <remarks/>
        public string FechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
            }
        }
        
        /// <remarks/>
        public int ParadaId {
            get {
                return this.paradaIdField;
            }
            set {
                this.paradaIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BusWS {
        
        private int idField;
        
        private string numeroRutaField;
        
        private bool estadoField;
        
        private byte[] fotoBusField;
        
        private string fechaCreacionField;
        
        private string usuarioCreacionField;
        
        private string fechaModificacionField;
        
        private string usuarioModificacionField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroRuta {
            get {
                return this.numeroRutaField;
            }
            set {
                this.numeroRutaField = value;
            }
        }
        
        /// <remarks/>
        public bool Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FotoBus {
            get {
                return this.fotoBusField;
            }
            set {
                this.fotoBusField = value;
            }
        }
        
        /// <remarks/>
        public string FechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
            }
        }
        
        /// <remarks/>
        public string FechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioModificacion {
            get {
                return this.usuarioModificacionField;
            }
            set {
                this.usuarioModificacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BusParadaWS {
        
        private int idField;
        
        private int paradaIdField;
        
        private int busIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ParadaId {
            get {
                return this.paradaIdField;
            }
            set {
                this.paradaIdField = value;
            }
        }
        
        /// <remarks/>
        public int BusId {
            get {
                return this.busIdField;
            }
            set {
                this.busIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultadoSW {
        
        private string mensajeField;
        
        private bool respuestaField;
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public bool respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AgregarParadaCompletedEventHandler(object sender, AgregarParadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarParadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarParadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EliminarParadaCompletedEventHandler(object sender, EliminarParadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarParadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarParadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoSW Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoSW)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EditarParadasCompletedEventHandler(object sender, EditarParadasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditarParadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditarParadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListarParadaCompletedEventHandler(object sender, ListarParadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarParadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarParadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ParadasWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ParadasWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListarParadaActivasCompletedEventHandler(object sender, ListarParadaActivasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarParadaActivasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarParadaActivasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ParadasWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ParadasWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EditarBusParadasCompletedEventHandler(object sender, EditarBusParadasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditarBusParadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditarBusParadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AgregarBusParadasCompletedEventHandler(object sender, AgregarBusParadasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarBusParadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarBusParadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EliminarBusesParadasCompletedEventHandler(object sender, EliminarBusesParadasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarBusesParadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarBusesParadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoSW Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoSW)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListarBusParadaCompletedEventHandler(object sender, ListarBusParadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarBusParadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarBusParadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BusParadaWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BusParadaWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AgregarBusCompletedEventHandler(object sender, AgregarBusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarBusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarBusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EliminarBusCompletedEventHandler(object sender, EliminarBusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarBusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarBusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoSW Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoSW)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListarBusCompletedEventHandler(object sender, ListarBusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarBusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarBusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BusWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BusWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListarBusActivosCompletedEventHandler(object sender, ListarBusActivosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarBusActivosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarBusActivosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BusWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BusWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EditarBusCompletedEventHandler(object sender, EditarBusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditarBusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditarBusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AgregarSugerenciaCompletedEventHandler(object sender, AgregarSugerenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarSugerenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarSugerenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EditarSugerenciaCompletedEventHandler(object sender, EditarSugerenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditarSugerenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditarSugerenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EliminaraSugerenciasCompletedEventHandler(object sender, EliminaraSugerenciasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminaraSugerenciasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminaraSugerenciasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoSW Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoSW)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListarSugerenciasCompletedEventHandler(object sender, ListarSugerenciasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarSugerenciasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarSugerenciasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SugerenciaWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SugerenciaWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListarSugerenciasPersonalesCompletedEventHandler(object sender, ListarSugerenciasPersonalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarSugerenciasPersonalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarSugerenciasPersonalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SugerenciaWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SugerenciaWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RolAnonimoCompletedEventHandler(object sender, RolAnonimoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RolAnonimoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RolAnonimoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CambiarClaveCompletedEventHandler(object sender, CambiarClaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CambiarClaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CambiarClaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CrearUsuarioCompletedEventHandler(object sender, CrearUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoSW Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoSW)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListarUsuariosCompletedEventHandler(object sender, ListarUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuariosWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuariosWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EliminarUsuarioCompletedEventHandler(object sender, EliminarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoSW Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoSW)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CrearUsuarioRolCompletedEventHandler(object sender, CrearUsuarioRolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearUsuarioRolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearUsuarioRolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoSW Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoSW)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591